Array is not usable as a type hint, so use something else
"Array[type]" causes errors when used as a type hint.
So let's change this to something better, Eg. MutableSequence

Traceback (most recent call last):
  File "basic_window.py", line 3, in <module>
    from raylibpy.colors import *
  File "/home/adam/Workspace/raylib-py/raylibpy/colors.py", line 1, in <module>
    import raylibpy.core as core
  File "/home/adam/Workspace/raylib-py/raylibpy/core.py", line 166, in <module>
    def _str_in2(values: Sequence[Union[str, bytes]]) -> Array[bytes]:
TypeError: '_ctypes.PyCArrayType' object is not subscriptable